-- Seed data for tbl_master_brand
INSERT INTO public.tbl_master_brand (id, name, type, isactive)
VALUES
(1, 'Almost Real Model', 'Diecast', 1),
(2, 'AmericanDiorama', 'Diorama', 1),
(3, 'Autoart', 'Diecast', 1),
(4, 'BMC', 'Diecast', 1),
(5, 'Bburago', 'Diecast', 1),
(6, 'CMModel', 'Diecast', 1),
(7, 'Clasic Lover', 'Diecast', 1),
(8, 'Custom Diorama - Indonesia Maker', 'Diorama', 1),
(9, 'Custom Diorama - Malaysia Maker', 'Diorama', 1),
(10, 'Custom Diorama - Thailand Maker', 'Diorama', 1),
(11, 'DCM', 'Diecast', 1),
(12, 'DCT', 'Diecast', 1),
(13, 'Fast & Speed', 'Diecast', 1),
(14, 'Finclassically', 'Diecast', 1),
(15, 'Focal Horizon', 'Diecast', 1),
(16, 'GCD', 'Diecast', 1),
(17, 'Gfans', 'Diorama', 1),
(18, 'Ghost Player', 'Diecast', 1),
(19, 'Greenlight', 'Diecast', 1),
(20, 'Hem Resin', 'Diecast', 1),
(21, 'Hobby Japan', 'Diecast', 1),
(22, 'Hot Wheels', 'Diecast', 1),
(23, 'IXO Models', 'Diecast', 1),
(24, 'Ignition Model', 'Diecast', 1),
(25, 'Inno Models', 'Diecast', 1),
(26, 'Jada Toys', 'Diecast', 1),
(27, 'Johnny Lightning', 'Diecast', 1),
(28, 'Kaido House', 'Diecast', 1),
(29, 'Kiloworks', 'Diecast', 1),
(30, 'Kyosho', 'Diecast', 1),
(31, 'LCD', 'Diecast', 1),
(32, 'LCD model', 'Diecast', 1),
(33, 'MJModel', 'Diecast', 1),
(34, 'MOREART Diorama', 'Diorama', 1),
(35, 'MOREART Figure', 'Accessory', 1),
(36, 'Magic City', 'Diorama', 1),
(37, 'Matchbox', 'Diecast', 1),
(38, 'Mcool', 'Diorama', 1),
(39, 'Microturbo', 'Diecast', 1),
(40, 'Minibike', 'Diecast', 1),
(41, 'Minichamps', 'Diecast', 1),
(42, 'Modelmodel', 'Diecast', 1),
(43, 'Moreart', 'Diecast', 1),
(44, 'Mortal Model', 'Diecast', 1),
(45, 'Motorhelix', 'Diecast', 1),
(46, 'My Model Collect', 'Diecast', 1),
(47, 'New Mortal', 'Diecast', 1),
(48, 'New Shadow', 'Diecast', 1),
(49, 'New Spark', 'Diecast', 1),
(50, 'Peako', 'Diecast', 1),
(51, 'Pop Race', 'Diecast', 1),
(52, 'SCJ Diorama', 'Diorama', 1),
(53, 'Spark', 'Diecast', 1),
(54, 'Star Model', 'Diecast', 1),
(55, 'Starrace', 'Diecast', 1),
(56, 'Tamiya', 'Diecast', 1),
(57, 'Tarmac Works', 'Diecast', 1),
(58, 'TimeMicro', 'Diecast', 1),
(59, 'Tomica', 'Diecast', 1),
(60, 'Tomy (TakaraTomy)', 'Diecast', 1),
(61, 'Tomytec', 'Diecast', 1),
(62, 'Top Art', 'Diecast', 1),
(63, 'Top Speed', 'Diecast', 1),
(64, 'Trends Hobby', 'Diecast', 1),
(65, 'Welly', 'Diecast', 1),
(66, 'WhelArt', 'Diecast', 1),
(67, 'Xcartoys', 'Diecast', 1)
ON CONFLICT (id) DO NOTHING;

